name: Fragments check

on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]
    branches:
      - master

jobs:
  check-fragment-added:
    if: github.event.pull_request.user.type != 'Bot' && !contains(github.event.pull_request.labels.*.name, 'skip-fragment-check')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # `towncrier check` runs `git diff --name-only origin/main...`, which
          # needs a non-shallow clone.
          fetch-depth: 2

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Check if changelog fragment was added
        run: |
          pip install towncrier

          if ! towncrier check --compare-with origin/${{ github.base_ref }}; then
            echo "----------------------------------------------------"
            echo "Please refer to CONTRIBUTING.md for more information"
            exit 1
          fi
